Console.log("Rodando o sistema de gerenciamento de jogos")
console.log("Acrescentando alteração via GitHub para visualisação de alterações no comando git pull no terminal")
;)
console.log("Retornando para GitHub alteração baixad via pull e enviando ela mais esta alteração")
>:)
